---
title: "R Basic"
author: "Charlene P. Garridos"
date: "2023-03-16"
output: 
  pdf_document:
    highlight: tango
---
# R Basic: Syntax, Command, Data Types, Variables, Operators, Functions, Vectors, List and Matrices

```{r, echo=TRUE}
my_sum <- 3+3
my_sum +3
```

```{r, echo=TRUE}
my_sum <- 3+3
my_list <- list
my_sum +3
```

```{r, echo=TRUE}
my_sum
```

```{r, echo=TRUE}
(another_sum <- 5+6)
```

```{r, echo=TRUE}
my_integer <- 1L
typeof(my_integer)
```

```{r, echo=TRUE}
my_integer <- 9
typeof(my_integer)
```

```{r, echo=TRUE}
my_character <- "This is Text"
typeof(my_character)
```

```{r, echo=TRUE}
(my_logical <- FALSE)
```

```{r, echo=TRUE}
typeof(my_logical)
```

```{r, echo=TRUE}
my_double <- 5.6
typeof(my_double)
```

```{r, echo=TRUE}
double_vec <- c(3.1, 31, 311, 3111, 3.111)
str(double_vec)
```

```{r, echo=TRUE}
categories <- factor(c("C", "H", "A", "R", "L"))
str(categories)
```

```{r, echo=TRUE}
categories_char <- c("C", "H", "A", "R", "L")
str(categories_char)
```

```{r, echo=TRUE}
ranking <- c("Medium", "High", "Low")
str(ranking)
```

```{r, echo=TRUE}
ranking_factors <- ordered(ranking, levels = c("Low", "Medium", "High"))
str(ranking_factors)
```

```{r, echo=TRUE}
length(categories)
```

```{r, echo=TRUE}
length(ranking_factors)
```

```{r, echo=TRUE}
(my_sequence <- 1:10)
```

```{r, echo=TRUE}
(my_sequence <- seq(from = 1, to = 10))
```

```{r, echo=TRUE}
my_seq_two <- seq(from = 1, to = 10, by = 5)
my_seq_two
```

```{r,echo=TRUE}
my_seq_three <- seq(from = 1, to = 10, by = 2)
my_seq_three
```

```{r, echo=TRUE}
vec <- 1:5
str(vec)
```

```{r, echo=TRUE}
new_vec <- c(vec, "hello")
str(new_vec)
```

```{r, echo=TRUE}
mix <- c(TRUE, 6)
str(mix)
```

```{r, echo=TRUE}
new_categories <- c(categories, 1)
str(new_categories)
```

```{r, echo=TRUE}
str(categories)
```

```{r, echo=TRUE}
(m <- matrix(c(1, 2, 3, 4), nrow = 2, ncol = 2))
```

```{r, echo=TRUE}
(m <- matrix(vec, nrow = 5, ncol = 2))
```

```{r, echo=TRUE}
my_list <- list(6, TRUE, "hello")
str(my_list)
```

```{r, echo=TRUE}
new_list <- list(scalar = 6, vector = c("Heloo", "Goodbye"), matrix = matrix(1:4, nrow = 2, ncol = 2))
str(new_list)
```

```{r, echo=TRUE}
new_list$matrix
```

```{r, echo=TRUE}
new_list$vec
```

